export const GET_POKEMON = "GET_POKEMON"
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS"
export const GET_POKEMON_FAILED = "GET_POKEMON_FAILED"

export const GET_POKEMON_DETAIL = "GET_POKEMON_DETAIL"
export const GET_POKEMON_DETAIL_SUCCESS = "GET_POKEMON_DETAIL_SUCCESS"
export const GET_POKEMON_DETAIL_FAILED = "GET_POKEMON_DETAIL_FAILED"

export const COMPARE_POKEMON = 'COMPARE_POKEMON';
export const COMPARE_POKEMON_SUCCESS = 'COMPARE_POKEMON_SUCCESS';
export const COMPARE_POKEMON_FAILED = 'COMPARE_POKEMON_FAILED';